config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/interests'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enrique Pajuelo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <link href='https://fonts.googleapis.com/css?family=Pompiere' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>


<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <div class="collapse navbar-collapse">
    	<ul class="nav navbar-nav navbar-right">
        	<li class="active"><a <%= link_to 'Home', welcome_index_path %></a></li>
        	<li class="active"><a <%= link_to 'About', welcome_about_path %></a></li>
        	<li class="active"><a <%= link_to 'Interests', welcome_interests_path %></a></li>

      	</ul>
    </div>

  </div>
</nav>

<br/>
<br/>
<br/>

 
<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<div class="aboutpage">

<header>

<br/><br/>
<h3>About</h3>
<br/><br/><br/>

<!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-6">
                	<h4><strong>What is this?</strong></h4>
                    <p>Hi there! I decided to build this website after finishing a coding boot camp in South Africa because I wanted people to learn more about me (and not just build an idea of who I am based on my resume). Please feel free to reach out and I hope you enjoy my website!</p>
                    <br/>
                </div>
                <div class="col-md-6 col-lg-6">
                	<h4><strong>Why am I doing this?</strong></h4>
                    <p>I am currently pursuing a double major in Finance and Economics at the University of Notre Dame and I wanted to build a space where I could compile all of the activities that I enjoy doing (and also the ones I don't do anymore but that shaped significantly who I am).</p>
                    <br/>
                </div>
            </div>
        </div>
    </section>

</header>

<!-- Footer -->
    <footer class="text-center">
        <div class="footer-below2">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                            <br/>
                            made by enrique pajuelo &copy; 2015
                            <br/><br/>
                    </div>
                </div>
            </div>
        </div>
    </footer>



</div>

app/views/welcome/index.html.erb
<div class="frontpage">

<header>

<br/><br/><br/><br/><br/><br/>
<h1>Enrique Pajuelo</h1>

    <ul class="list-inline">
      	<li><a href="/documents/resume.pdf" class="btn-social btn-outline"><i class="fa fa-fw fa-file-text-o"></i></a></li>
        <li><a href="https://open.spotify.com/user/epajueloc" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-spotify"></i></a></li>
        <li><a href="http://pe.linkedin.com/in/epajueloc" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a></li>
        <li><a href="https://calendly.com/epajueloc" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-calendar"></i></a></li>
        <li><a href="mailto:epajuelo@nd.edu?Subject=Just wanted to say hi" class="btn-social btn-outline"><i class="fa fa-fw fa-envelope-o"></i></a></li>
    </ul>

<br/>
     
     <span class="skills">Finance and Economics | University of Notre Dame '18 </span>

</header>

<!-- Footer -->
    <footer class="text-center">
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                            <br/><br/>
                            made by enrique pajuelo &copy; 2015
                            <br/><br/>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</div>

app/views/welcome/interests.html.erb
<div class="interestspage">

<header>

<br/><br/>
<h3>Interests</h3>

  <div class="row">

    <div class="form1">
      <h4>Get to know me</h4>
      <hr>

        <div class="col-md-4">
        <p>I'm a Finance and Economics double major at the University of Notre Dame and am very passionate about finance, entrepreneurship and sports. I'm the President of the Entrepreneurship Society of Notre Dame and love learning about new ways in which technology can shape our lives.</p>
        </div>

        <div class="col-md-4">
        <p>I'm originally from Lima, Peru and even though I love the people, the music, and the food back home, I decided that studying in the United States would be best for my personal and professional development. I chose to come to Notre Dame not only because of its excellent academic program and prestigious business school, but also because of the spiritual aspect that it offers.</p>
        </div>

        <div class="col-md-4">
        <p>I believe that businesses are the best way to give back to society. Not only can a business affect its employees and their families, but it can also help change whole communities. I believe that finance is a great way to achieve this because it helps businesses and individuals achieve their growth goals by adivising them on how to best use their capital.</p>
        </div>

    </div>
</div>

<div class="images">
<div class="row">

  <div class="col-md-12">
    <img src="/assets/linkedin.jpg">
  </div>

</div>
</div>  

<div class="row">

      <div class="form2">
       <h4>Relevant experience</h4>
       <hr>

      <div class="col-md-4">

       <h5>Diviso Fondos<h6>June 2015 - August 2015 | Lima, Peru</h6></h5>
       <hr>
        <p>Following my freshman year, I interned in the Sales and Trading division of Diviso Fondos, an Investment Company in Peru. It was my first exposure to the financial world and I learned way more than I expected.</p>
        <p>I elaborated and analyzed daily and monthly reports related to the performance of the mutual funds. I consolidated the data into written reports, and created presentations that were used by the CEO at Board meetings.</p>
        <p>I supported the porfolio managers at the trading desk in their transactions by providing relevant information obtained from a Bloomberg terminal.</p><br/>

      </div>

      <div class="col-md-4">

        <h5>Adventis CG<h6>October 2016 - October 2016 | Lima, Peru</h6></h5>
        <hr>

        <p>This semester I took the Adventis CG Financial Modeling Course at Notre Dame, in which we built a three-statement, fully circular and properly formatted financial model from scratch in under 90 minutes.</p>
        <p>This was an intense course in which I deepened my understanding of the concepts learned in the classroom and that helped me develop an understanding of key concepts in financial modeling, accounting and corporate finance, instrinsic and relative valuation and leveraged buyout (LBO) transctions including EBITDA, DCF and WACC.</p><br/>

      </div>

      <div class="col-md-4">

        <h5>Ladrillos Fortes<h6>January 2014 - April 2014 | Lima, Peru</h6></h5>
        <hr>

        <p>Ladrillos Fortes is a Peruvian brick company with factories in four different cities in Peru. I worked as a Sales and Marketing Intern, and my main duty was to help the division unify information accross the Sales, Marketing and Production Departments to optimize the planning strategy of the sale of ceramic bricks, by reducing remaining stock and fulfilling customer orders in time.</p>
        <p>This was to be achieved by researching new markets through one-on-one conversations, phone calls, surveys and visiting retailers.</p>

      </div>

    </div>
    </div>

<div class="images">
<div class="row">

  <div class="col-md-12">
    <img src="/assets/dab.jpg">
  </div>

</div>
</div> 

    <div class="row">

      <div class="form3">
       <h4>Traveling</h4>
       <hr>

      <div class="col-md-4">

       <h5>iXperience<h6>Summer 2015 & Summer 2016 | Cape Town, South Africa</h6></h5>
       <hr>
        <p>I attended two intensive, 160-hour coding camps in Cape Town. I met people from top universities worldwide, ate amazing food, discovered awesome places and, most importantly, learned how to code.</p>
        <p>I designed and created a dynamic web application called Bridge, using Ruby on Rails, HTML, and CSS. Bridge is a platform designed to connect clients directly to freelancers, inspired by the increasing unemployment in South Africa. Check it out! <font color="blue"><u>(www.bridgeconnect.co)</u></font></p>
        <p>I also developed an iOS app that helps reduce meat intake by displaying a dynamic calendar that keeps track of your goals, collaborating with the UX Design and PM teams.</p><br/>
      </div>

       <div class="col-md-4">

        <h5>SIBC International Case Study<h6>October 2015 | Sao Paulo, Brazil</h6></h5>
        <hr>

        <p>During Fall Break of my sophomore year, I traveled with a delegation of six other Notre Dame students to Brazil to participate in a program with workshops, lectures, and cultural immersion, as well as a case study with students from the University of Campinas.</p>
        <p>It was a great opportunity to work on an international topic with students from diverse backgrounds and to develop global business knowledge and skills. I learned in depth about Brazil's socio-economic situation from the perspective of students, professors, tour guides, and even from the taxi drivers (with whom I got to practice my Portuguese as well!).</p><br/>

      </div>

      <div class="col-md-4">

        <h5>Round Square International Conference<h6>2012 | Nairobi, Kenya</h6></h5>
        <hr>

        <p>My senior year in high school, I attended a conference held in Nairobi with around 300 delegates from around the world. Before attending the actual conference, we went to Mombasa (a beach nearby) and we also went on a safari. This made my first time in Africa an amazing experience.</p>
        <p>The theme of the conference was "No existence without coexistence", which raised awareness of Africa's socio-political issues. I stayed in the house of Kenyian students, and attended several workshops where we discussed our different views of topics related to the theme. We also helped build school classrooms for poor children.</p>

      </div>

    </div>
    </div>

<div class="images">
<div class="row">

  <div class="col-md-12">
    <img src="/assets/sandboarding.jpg">
  </div>

</div>
<div class="row">

  <div class="col-md-12">
    <img src="/assets/surf2.jpg">
  </div>

</div>
</div> 

    <div class="row">

      <div class="form4">
       <h4>Clubs and societies</h4>
       <hr>

      <div class="col-md-4">

       <h5>Entrepreneurship Society of Notre Dame<h6>President</h6></h5>
       <hr>
        <p>The E-Society is a student-led organization that empowers aspiring entrepreneurs of all academic interests to translate their passions into action.</p>
        <p>I identified the need for an entrepreneurial ecosystem on campus and developed a plan to implement a series of changes to a dormant club, such as startup workshops, guest speaker events and fundraising opportunities throughout the year. In my first year as President we increased the number of active members by 250% by creating a network of support and learning resources.</p>
      </div>


       <div class="col-md-4">

        <h5>Student International Business Council<h6>Member</h6></h5>
        <hr>

        <p>I got involved in SIBC on my first semester in college, and did projects in the finance and consulting divisions. One of the projects had us simulate the work done by investment banking analysts through qualitative and quantitative analysis related to an IPO, utilizing public information and market research.</p>
        <p>More recently, I have been involved in the International Experiences teams, traveling to Brazil and leading a project in which we are going to host a group of students from Unicamp (Brazil) here at Notre Dame.</p>
        <br/>

      </div>

      <div class="col-md-4">

        <h5>Other clubs and activities on campus<h6>Active</h6></h5>
        <hr>

        <p>Besides the two clubs I have already mentioned, I am also part of others clubs such as ALPFA (Association of Latino Professionals For America), the Wall Street Club, and the Latino Honors Society. These clubs have regular meetings and networking events to which I attend depending on the subject to be discussed. For example, in 2015 I traveled with the WSJ to Chicago to visit five financial firms (JP Morgan, Northern Trust, Baird, William Blair and Grosvenor).</p>

      </div>

    </div>
    </div>

<div class="images">
<div class="row">

  <div class="col-md-12">
    <img src="/assets/photo1.JPG">
  </div>

</div>
</div> 

</header>

<br/><br/>

<!-- Footer -->
    <footer class="text-center">
      <div class="footer-below3">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              made by enrique pajuelo &copy; 2015
            </div>
          </div>
        </div>
      </div>
    </footer>

</div>